title: "Martyn Steel"
description: "Postgraduate Research in Computational Geophysics at the University of Edinburgh"
taglong: Postgraduate Researcher
tagshort: PhD Student
baseurl: ""
url: https://martynsteel.github.io
permalink: /:title/
repo: https://github.com/MartynSteel/martynsteel.github.io

# Author settings
author:
  name: Martyn Steel
  email: martyn.steel@ed.ac.uk

# Social media settings

social:
  github: MartynSteel
  linkedin: martyn-steel

academic:
  orcid: 0000-0002-3140-9170
  google_scholar: https://scholar.google.com/citations?user=ReLhnkYAAAAJ&hl=en

# Build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
